### BUILD-ARM
kind: pipeline
name: build-arm

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      password:
        from_secret: docker_password
      tags: dev-arm
    when:
      event: push

  - name: build & push
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      password:
        from_secret: docker_password
      tags: 
        - arm
        - ${DRONE_TAG}-arm
    when:
      event: tag

trigger:
  event:
    - tag
    - push

---
### BUILD-ARM64
kind: pipeline
name: build-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      password:
        from_secret: docker_password
      tags: dev-arm64
    when:
      event: push

  - name: build & push
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      password:
        from_secret: docker_password
      tags: 
        - arm64
        - ${DRONE_TAG}-arm64
    when:
      event: tag

trigger:
  event:
    - tag
    - push

---
### BUILD-AMD64
kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      password:
        from_secret: docker_password
      tags: dev-amd64
    when:
      event: push

  - name: build & push
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      password:
        from_secret: docker_password
      tags: 
        - amd64
        - ${DRONE_TAG}-amd64
    when:
      event: tag

trigger:
  event:
    - tag
    - push

---
### MULTIARCH
kind: pipeline
name: multiarch

steps:
  - name: manifest latest
    image: plugins/manifest
    settings:
      username: ramosisw
      password:
        from_secret: docker_password
      target: ramosisw/openvpn:dev
      template: ramosisw/openvpn:dev-ARCH
      platforms:
        - linux/arm
        - linux/arm64
        - linux/amd64
    when:
      event: push

  - name: manifest latest
    image: plugins/manifest
    settings:
      username: ramosisw
      password:
        from_secret: docker_password
      target: ramosisw/openvpn:latest
      template: ramosisw/openvpn:ARCH
      platforms:
        - linux/arm
        - linux/arm64
        - linux/amd64
    when:
      event: tag

  - name: manifest ${DRONE_TAG}
    image: plugins/manifest
    settings:
      username: ramosisw
      password:
        from_secret: docker_password
      target: ramosisw/openvpn:${DRONE_TAG}
      template: ramosisw/openvpn:${DRONE_TAG}-ARCH
      platforms:
        - linux/arm
        - linux/arm64
        - linux/amd64
    when:
      event: tag

trigger:
  event:
    - tag
    - push

depends_on:
 - build-arm
 - build-arm64
 - build-amd64
