kind: pipeline
name: build-arm

platform:
  os: linux
  arch: arm

steps:
  - name: build and push
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      tags: 
        - arm
      password:
        from_secret: docker_password
trigger:
  event:
    - tag

---

kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build and push
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      repo: ramosisw/openvpn
      username: ramosisw
      tags: 
        - amd64
      password:
        from_secret: docker_password
trigger:
  event:
    - tag

---

kind: pipeline
name: multiarch

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username: ramosisw
      password:
        from_secret: docker_password
      target: ramosisw/openvpn:latest
      template: ramosisw/openvpn:ARCH
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64

# depends_on:
#  - build-arm
#  - build-amd64